version: "3"

services:
  caprover:
    container_name: caprover
    image: caprover/caprover

    volumes:
      - /captain:/captain
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
  jenkins:
    container_name: jenkins
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - /var/jenkins_home:/var/jenkins_home

    restart: always