version: "3"

services:
  caprover:
    container_name: caprover
    image: caprover/caprover

    volumes:
      - /captain:/captain
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
  jenkins:
    container_name: jenkins
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    #ports:
    #  - 8080:8080
    #  - 50000:50000
    privileged: true
    user: "1201:1201"
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /captain:/captain
      - ~/.docker:/var/jenkins_home/.docker 

    restart: always